apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name }}
rules: []  # no permissions

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRole.name }}-binding
subjects:
  - kind: ServiceAccount
    name: dev
    namespace: dev
  - kind: ServiceAccount
    name: qc
    namespace: staging
  - kind: ServiceAccount
    name: ops
    namespace: prod
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterRole.name }}
  apiGroup: rbac.authorization.k8s.io
