apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev
  namespace: dev

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-dev
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
