apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.deployment.name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.deployment.port }}
      targetPort: {{ .Values.deployment.port }}
