# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: {{ .Values.namespace }}
#   name: {{ .Values.secret.name }}
# type: {{ .Values.secret.type }}
# data:
#   DB_NAME:
#   DB_USER:
#   DB_PASSWORD:
