# Block all traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Values.namespace }}
  name: block-all
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.statefulset.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []

---
# Only allow flask to access postgres
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Values.namespace }}
  name: allow-flask-to-postgres
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.statefulset.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: flask
      ports:
        - protocol: TCP
          port: {{ .Values.statefulset.port }}
