apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    app: {{ .Values.statefulset.name }}
  ports:
    - port: {{ .Values.statefulset.port }}
      targetPort: {{ .Values.statefulset.port }}
