apiVersion: v2
name: app-stack
version: 0.1.0
dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: database
    version: 0.1.0
    repository: "file://charts/database"
