apiVersion: v2
name: app-stack
version: 0.1.0
dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: kube-prometheus-stack
    version: 79.2.1
    repository: https://prometheus-community.github.io/helm-charts
