backend:
  deployment:
    replicas: 1
    strategy:
      type: Recreate
    image:
      tag: latest
      # tag: broken
    requests:
      cpu: 100m
      mem: 128Mi
    limits:
      cpu: 250m
      mem: 256Mi

  monitor:
    endpoints:
      interval: 5s

  hpa:
    minReplicas: 1
    maxReplicas: 2
    metrics:
      resource:
        target:
          avgUtilization: 70

database:
  statefulset:
    replicas: 1
    requests:
      cpu: 100m
      mem: 128Mi
    limits:
      cpu: 250m
      mem: 256Mi
    volumeClaimTemplates:
      resources:
        requests:
          storage: 500Mi

# We don't use this value for any charts or templates
# I put it here just for helper scripts
namespace: dev
